### ISSUE TITLE
Module block syntax deprecated

### ISSUE THREAD

**Issue by kdex** [hemanth/paws-on-es6#10]
Currently, `modules.js` presents the module block syntax that has been removed from the spec a year ago. The syntax has been changed from this:

```js
/* In math.js */
module math {
	export function div(x, y) {
		return x / y;
	}
	export var pi = 3.141593;
}
```
to that:

```js
/* In math.js */
export function div(x, y) {
	return x / y;
}
export var pi = 3.141593;
```

**Comment by hemanth** [comment]
^ Yes have been using the second on all over [1-liners](https://github.com/1-liners/1-liners) thanks for highlighting that.

**Comment by hemanth** [comment]
BTW you might want to solve [this](http://es-discourse.com/t/short-hand-module-syntax/143)
