### ISSUE TITLE
misleading arrow example

### ISSUE THREAD

**Issue by garthk** [hemanth/paws-on-es6#6]
I'm not sure the constructor-like example in `arrow.js` from 844241b7 is correct.

According to @lukehoban's [ES6 Features](https://github.com/lukehoban/es6features#arrows) document cited by the Babel team:

> arrows share the same lexical `this` as their surrounding code

According to @sebmck in a [comment](https://github.com/babel/babel/issues/730#issuecomment-73506188) before closing babel/babel#730:

> Top level `this` is undefined ES6 modules as they're implicitly strict mode. 
> Arrow functions inherit the outer `this`.

The practical upshot of which is that your `Person` example isn't the constructor you might think it is. Inside the function, `this` *cannot* refer to a constructed object. Instead, `this` is `undefined`. As Babel transpiles it:

```js
var Person = function (fname, lname, age) {
   undefined.fname = fname;
   undefined.lname = lname;
   undefined.age = age;
   undefined.yo = function () {
      return "Yo! I'm " + undefined.fname + "!";
   }; // `this` reffers to Person.
};
```

Make `Person` an ES6 class or ES5 constructor function, and `yo` works as you expect:

```js
// ES6
class Person {
    constructor(fname, lname, age) {
       this.fname= fname;
       this.lname = lname;
       this.age = age;
       this.yo = () => `Yo! I'm ${this.fname}!`; // `this` refers to Person.
    }
}

// ES5
function Person(fname, lname, age) {
   this.fname= fname;
   this.lname = lname;
   this.age = age;
   this.yo = () => `Yo! I'm ${this.fname}!`; // `this` refers to Person.
}
```

**Comment by hemanth** [comment]
@garthk Thanks for highlighting `this` ;) 

Will update it with something more simpler like:

```js
let obj = {
  method: function () {
    return () => this;
  }
};
// Due to lexical scope obj.method()() <===> obj
```

It's worth noting:

```js
let meow = () => "meow"
```
is same as:

```js
meow = (function(){return "meow"}).bind(this);
```

The `bind(this)` part babel does not do and it has it's own reasons for that.
