### ISSUE TITLE
No need for strict mode 

### ISSUE THREAD

**Issue by michaelBenin** [hemanth/paws-on-es6#8]
https://github.com/hemanth/paws-on-es6/blob/master/tail-recursion.js#L2

**Comment by hemanth** [comment]
Sorry for the delay, any particular reason?

**Comment by michaelBenin** [comment]
Es6 modules are always in strict mode.

**Comment by hemanth** [comment]
But arrow functions do need them:

>Class, Modules implicitly strict. Arrows not strict Sustaining our position on the handling of let ambiguities

[Notes](https://github.com/rwaldron/tc39-notes/blob/master/es6/2013-01/jan-30.md)

**Comment by michaelBenin** [comment]
So for every arrow function we should add a ```'use strict'``` ?

**Comment by hemanth** [comment]
AFAIK.

//cc @ljharb

**Comment by ljharb** [comment]
Yes. However, you should just set it at the file level for all of your commonJS modules anyways.

**Comment by hemanth** [comment]
:+1: Agree. But for this sample, it looks fine. Thanks for the confirmation.
