### ISSUE TITLE
Array comprehensions were dropped from ES6

### ISSUE THREAD

**Issue by kdex** [hemanth/paws-on-es6#9]
Array comprehensions are not part of the standard, ES6/2015.

ES7/2016 array comprehensions are still in discussion. But right now, it doesn't look like they're going to make it into ES7/2016 either, as [no one's championing them](https://code.google.com/p/v8/issues/detail?id=2856) anymore.

Nontheless, it's misleading to show it as an example for ES6, so it should be removed.

**Comment by hemanth** [comment]
Oh yeah, totally forgot the remove them, I shall soon, thanks.
